{
  description = "flox-controller — FloxEnv CRD + node-agent controller for runtime flox-env delivery";

  # Follow the seedmatic aggregator so the whole closure resolves to one nixpkgs
  # (same discipline as flox-nri-plugin / rke2lab runtime-flox).
  inputs = {
    flake-commons.url = "github:seedmatic/nix-flake-commons/develop";
    nixpkgs.follows = "flake-commons/nixpkgs";
    flake-utils.follows = "flake-commons/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        version = pkgs.lib.fileContents ./VERSION;
      in
      {
        packages = rec {
          # The controller binary. Static (CGO off) so it runs in a minimal image.
          flox-controller = pkgs.buildGoModule {
            # Store-name prefix io.seedmatic.<asset> (org convention, was io.nxmatic
            # before the seedmatic move) so the artifact is findable in /nix/store;
            # meta.mainProgram keeps the bin at bin/flox-controller for `nix run`.
            pname = "io.seedmatic.flox-controller";
            inherit version;
            src = ./.;
            # Deterministic vendoring of the Go deps. Regenerate after a go.mod change:
            # set to lib.fakeHash, `nix build`, then paste the hash nix prints.
            vendorHash = "sha256-TRKTDXhNP6NNtH0YNWy2tTzhZ6XeQOtgoEfPJk44Gsw=";
            subPackages = [ "cmd/flox-controller" ];
            env.CGO_ENABLED = 0;
            ldflags = [ "-s" "-w" "-X main.version=${version}" ];
            meta.mainProgram = "flox-controller";
          };

          # OCI image for the node-agent DaemonSet — the DISTRIBUTION artifact.
          # Air-gap path (as for flox-carrier): the consumer (rke2lab) bakes this tar
          # into the node-base image via a tmpfiles symlink into
          # /var/lib/rancher/rke2/agent/images/, rke2 auto-imports it into local
          # containerd at boot, and the DaemonSet references
          # `io.seedmatic.flox-controller:<version>` with imagePullPolicy: IfNotPresent.
          # nix is NOT in the image: the controller execs the NODE's nix (host /nix
          # mounted in) to realise closures onto the host store.
          # NOTE: dockerTools can't build on darwin — build on the aarch64-linux
          # builder (`nix build .#flox-controller-image --system aarch64-linux --max-jobs 0`).
          flox-controller-image = pkgs.dockerTools.buildLayeredImage {
            # OCI name doubles as the store-path basename → same io.seedmatic.<asset>
            # prefix for store discoverability + a self-evident image ref.
            name = "io.seedmatic.flox-controller";
            tag = version;
            # The controller mounts the HOST /nix at /nix (to realise closures + GC-roots and
            # exec the node's flox/nix/ctr) — which SHADOWS the image's own /nix/store. So its
            # binary + cacert must be REAL files OUTSIDE /nix, else the entrypoint (and any
            # /nix/store path) dangles under the mount — the chicken-and-egg. Same real-file
            # lesson as the flox carrier's /etc. The Go binary is static (CGO off) → a plain copy
            # runs standalone; it needs the mounted /nix only to FIND flox/nix/ctr on PATH.
            extraCommands = ''
              mkdir -p usr/local/bin etc/ssl/certs
              cp ${flox-controller}/bin/flox-controller usr/local/bin/flox-controller
              cp ${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt etc/ssl/certs/ca-bundle.crt
            '';
            config = {
              Entrypoint = [ "/usr/local/bin/flox-controller" ];
              Env = [ "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt" ];
            };
          };

          # The generated CRD(s) as a store artifact — the single source consumers
          # (rke2lab's manifest synthesis) emit into the cluster's `crds` layer,
          # instead of re-modelling the schema. Regenerated by `controller-gen crd`
          # (see the flox dev env); this just stages the committed output.
          flox-controller-crds = pkgs.runCommand "io.seedmatic.flox-controller-crds" { } ''
            mkdir -p "$out"
            cp ${./config/crd}/*.yaml "$out"/
          '';

          default = flox-controller;
        };

        # Dev toolchain lives in the flox env (.flox/env/manifest.toml): `flox activate`
        # provides go, controller-gen, kubectl, delve, make.
      });
}
